//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automate()
        {
            this.Redresseur = new HashSet<Redresseur>();
        }
    
        public int Id { get; set; }
        public string Mode { get; set; }
        public string IpAdresse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redresseur> Redresseur { get; set; }
    }
}
