//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public System.DateTime Date { get; set; }
        public int IdRedresseur { get; set; }
        public int IdUtilisateur { get; set; }
        public string OrdreFabrication { get; set; }
        public string EtatFin { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
    
        public virtual Redresseur Redresseur { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
