//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public System.DateTime Date { get; set; }
        public int IdRedresseur { get; set; }
        public int IdUtilisateur { get; set; }
        public string OrdreFabrication { get; set; }
        public string EtatFin { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Type { get; set; }
    
        public virtual Redresseur Redresseur { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
