//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public int Id { get; set; }
        public int IdRedresseur { get; set; }
        public int IdSegment { get; set; }
        public int IdRecette { get; set; }
        public int IdProcess { get; set; }
        public string Nom { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Recette Recette { get; set; }
        public virtual Redresseur Redresseur { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
