//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registre
    {
        public int Id { get; set; }
        public int IdRedresseur { get; set; }
        public string Nom { get; set; }
        public string TypeModbus { get; set; }
        public string Type { get; set; }
        public int AdresseDebut { get; set; }
        public int AdresseFin { get; set; }
        public int NumBit { get; set; }
    
        public virtual Redresseur Redresseur { get; set; }
    }
}
