//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registre
    {
        public int Id { get; set; }
        public int IdRedresseur { get; set; }
        public string Nom { get; set; }
        public string TypeModbus { get; set; }
        public string Type { get; set; }
        public int AdresseDebut { get; set; }
        public int AdresseFin { get; set; }
        public int NumBit { get; set; }
    
        public virtual Redresseur Redresseur { get; set; }
    }
}
