//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Segment()
        {
            this.Options = new HashSet<Options>();
        }
    
        public int Id { get; set; }
        public int IdRecette { get; set; }
        public string Nom { get; set; }
        public bool Etat { get; set; }
        public string Type { get; set; }
        public System.TimeSpan Duree { get; set; }
        public int ConsigneDepartV { get; set; }
        public int ConsigneDepartA { get; set; }
        public int ConsigneArriveeV { get; set; }
        public int ConsigneArriveeA { get; set; }
        public Nullable<System.TimeSpan> TempsRestant { get; set; }
        public Nullable<bool> Pulse { get; set; }
        public Nullable<bool> Temporisation { get; set; }
        public Nullable<System.TimeSpan> TempsOn { get; set; }
        public Nullable<System.TimeSpan> TempsOff { get; set; }
        public Nullable<bool> AH { get; set; }
        public Nullable<int> CompteurAH { get; set; }
        public string CalibreAH { get; set; }
        public Nullable<bool> Rampe { get; set; }
        public Nullable<System.TimeSpan> DureeRampe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Options> Options { get; set; }
        public virtual Recette Recette { get; set; }
    }
}
