//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataService
{
    public partial class HistoriqueData
    {

        #region CONSTRUCTEUR(S)/DESTRUCTEUR(S)
        public HistoriqueData()
        {

        }
        #endregion

        #region METHODS

        #endregion
    }
}
