//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcoreDBEntities : DbContext
    {
        public AcoreDBEntities()
            : base("name=AcoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Automate> Automate { get; set; }
        public virtual DbSet<Historique> Historique { get; set; }
        public virtual DbSet<HistoriqueData> HistoriqueData { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Recette> Recette { get; set; }
        public virtual DbSet<Redresseur> Redresseur { get; set; }
        public virtual DbSet<Registre> Registre { get; set; }
        public virtual DbSet<Segment> Segment { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
