//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historique()
        {
            this.HistoriqueData = new HashSet<HistoriqueData>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateDebut { get; set; }
        public int IdUtilisateur { get; set; }
        public int IdRedresseur { get; set; }
        public Nullable<int> IdRecette { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string OrdreFabrication { get; set; }
        public string EtatFin { get; set; }
        public string Type { get; set; }
    
        public virtual Recette Recette { get; set; }
        public virtual Redresseur Redresseur { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueData> HistoriqueData { get; set; }
    }
}
