//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public int Id { get; set; }
        public int IdRedresseur { get; set; }
        public int IdSegment { get; set; }
        public int IdRecette { get; set; }
        public int IdProcess { get; set; }
        public string Nom { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Recette Recette { get; set; }
        public virtual Redresseur Redresseur { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
