//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcoreApplication.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Redresseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Redresseur()
        {
            this.Historique = new HashSet<Historique>();
            this.Options = new HashSet<Options>();
            this.Registre = new HashSet<Registre>();
        }
    
        public int Id { get; set; }
        public string IpAdresse { get; set; }
        public int IdProcess { get; set; }
        public bool OnOff { get; set; }
        public bool MiseSousTension { get; set; }
        public string Etat { get; set; }
        public string Type { get; set; }
        public Nullable<double> CalibreV { get; set; }
        public int UMax { get; set; }
        public Nullable<double> CalibreA { get; set; }
        public int IMax { get; set; }
        public int ConsigneV { get; set; }
        public int ConsigneA { get; set; }
        public Nullable<int> LectureV { get; set; }
        public Nullable<int> LectureA { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<bool> AH { get; set; }
        public Nullable<int> CompteurAH { get; set; }
        public string CalibreAH { get; set; }
        public Nullable<bool> Inverseur { get; set; }
        public bool Prevent { get; set; }
        public Nullable<bool> Pulse { get; set; }
        public Nullable<int> TempsOn { get; set; }
        public Nullable<int> TempsOff { get; set; }
        public Nullable<bool> Temporisation { get; set; }
        public Nullable<System.TimeSpan> DureeTempo { get; set; }
        public Nullable<System.TimeSpan> DureeRestante { get; set; }
        public Nullable<bool> Rampe { get; set; }
        public Nullable<System.TimeSpan> DureeRampe { get; set; }
        public byte[] FichierIncident { get; set; }
        public bool Defaut { get; set; }
    
        public virtual Automate Automate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historique> Historique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Options> Options { get; set; }
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registre> Registre { get; set; }
    }
}
